// QUICK PSEUDOCODE TEMPLATE
// --------------------------
// EXPORT MODULE
// ALL_LEAGUES = LEAGUE.FIND_ALL($LTE TODAY)
// SORT_LEAGUES = ALL_LEAGUES.MAP(LEAGUE => LEAGUE.PLAYER_LIST.MAP(PLAYER => { _id: PLAYER._id, GROWTH: (PLAYER.END_MONEY - PLAYER.START_MONEY) / PLAYER.START_MONEY }).SORT((PLAYER1,PLAYER2) => PLAYER1.GROWTH < PLAYER2.GROWTH ? -1 : PLAYER1.GROWTH > PLAYER2.GROWTH ? 1 : 0 ))
// SORTED_LEAGUES.FOREACH(LEAGUE => LEAGUE.FOREACH((PLAYER,INDEX) => PLAYER._id.CURRENCY += 10000 * LEAGUE.AMOUNT_OF_PLAYERS * LEAGUE.DURATION_IN_DAYS * (1 / INDEX) ))
//
//
//
// SIMPLIFIED
// -----------
// 0. EXPORT MODULE
// 1. FIND ALL LEAGUES THAT HAVE AN END DATE BEFORE CURRENT DATE (SEARCH LEAGUE DATABASE)
// 2. RANK ALL PLAYERS BASED ON GROWTH
// 3. DISTRIBUTE CURRENCY BASED ON RANK (FIND AND UPDATE USER DATABASE)
